-  name: Install Packages.
   package:
     name:
       - htop
       - vim
       - git
       - dconf-cli
       - code 

-  name: Copy wallpaper file.
   copy:
     src: files/wallpaper.png
     dest: /usr/share/backgrounds/ansible-wallpaper.png
     owner: root
     group: root

-  name: Set Wallpaper.
   become_user: mikael
   dconf:
     key: "/org/gnome/desktop/background/picture-uri"
     value: "'file:///user/share/backgrounds/ansible-wallpaper.png'"

-  name: Set Wallpaper position.
   become_user: mikael
   dconf:
     key: "/org/gnome/desktop/background/picture-options"
     value: "'zoom'"

-  name: Add Microsoft GPG Key.
   apt_key:
     url: https://packages.microsoft.com/keys/microsoft.asc
     state: present

-  name: Add microsoft repo. 
   apt_repository:
     repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
     state: present